FROM data_ingestor:latest

# Copy requirements file into the container
COPY services/data-ingestor/requirements.test.txt .

# Install dependencies specified in requirements.test.txt
RUN pip install --no-cache-dir -r requirements.test.txt --root-user-action=ignore

COPY services/data-ingestor/test /test
COPY services/data-ingestor/.env.example /app/.env