FROM python:3.13-slim

# Copy requirements file into the container
COPY services/CovidDataSimulator/environments/dev/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt --root-user-action=ignore

# Copy all project files into the container
COPY services/CovidDataSimulator/app /app
# copy .env file
COPY services/CovidDataSimulator/environments/dev/.env.dev /app/.env
# copy utils
COPY utils /app/utils

ENV PYTHONPATH=/app
WORKDIR /app

CMD ["python", "main.py"]