FROM python:3.13-slim

# Copy requirements file into the container
COPY services/CovidDataSimulator/environments/dev/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt --root-user-action=ignore

# Copy all project files into the container
COPY services/CovidDataSimulator/app /app
# copy utils
COPY utils /app/utils
# copy data
COPY services/CovidDataSimulator/environments/shared/data /data

ENV PYTHONPATH=/app
WORKDIR /app

CMD ["python", "main.py"]