FROM safezone_analytics_api:latest

# ===== the following lines are added for test =====
COPY services/analytics-api/requirements.test.txt .
# Install test dependencies specified in requirements.test.txt
RUN pip install --no-cache-dir -r requirements.test.txt --root-user-action=ignore

# copy .env file
COPY services/analytics-api/test/tests /test
COPY services/analytics-api/.env.example /app/.env
# copy test data and pregenerated db
COPY services/analytics-api/test/data /data
COPY services/analytics-api/test/db /db


