FROM python:3.13-slim

# Copy requirements file into the container
COPY services/SafeZoneDashboard/environments/dev/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt --root-user-action=ignore

# Copy all project files into the container
COPY services/SafeZoneDashboard/app /app
# copy utils
COPY utils /app/utils
# copy .env file
COPY services/SafeZoneDashboard/environments/dev/.env.dev /app/.env

ENV PYTHONPATH=/app