name: Run testing ci for dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check dir
        run: ls -R
      - name: Run Dockerized Tests
        run: make test-all

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v4
      - name: check dir
        run: ls -R
      - name: Build Docker Image
        run: make build-all

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - uses: actions/checkout@v4
      - name: check dir
        run: ls -R
      - name: Deploy Docker Compose
        working-directory: local/compose
        run: |
          echo "Working dir: $(pwd)"
          docker compose local/compose/dev-ci.yml up -d