name: local act workflow for feature branch

# For testing purposes only.
# Do not use for production deployment.

on:
  push:
    branches:
      - feature/*
      - refactor/*

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all files
        run: ls -R

      - name: Run Dockerized Tests
        run: make test-all

  build:
    runs-on: self-hosted
    # needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all files
        run: ls -R

      - name: Build Docker Images
        run: make build-all
  
  # convert .secrets data to .env.secret for compose usage
  compose:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env.secret
        run: |
          cat <<EOF > .env.secret
          CLIENT_ID=${{ secrets.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}
          EOF

      - name: Run Docker Compose phase-1
        env:
          COMPOSE_PROFILES: infra        
        run: |
          cat .env.secret
          docker compose -f docker-compose/dev_compose.yml up -d
      
      - name: Wait for CLI container ready
        run: sleep 5

      - name: run db seed
        run: |
          export CLI_CONTAINER=$(docker ps --filter "name=cli-command" --format "{{.Names}}" | head -n 1)
          docker exec $CLI_CONTAINER szcli db init

      - name: Run Docker Compose phase-2
        env:
          COMPOSE_PROFILES: core
        run: docker compose -f docker-compose/dev_compose.yml up -d
      
      - name: run db seed 2
        run: |
          export CLI_CONTAINER=$(docker ps --filter "name=cli-command" --format "{{.Names}}" | head -n 1) 
          docker exec docker-compose-cli-command-1 bash -c "scripts/init.sh"
      
      - name: Wait for CLI container ready
        run: sleep 5

      - name: Run Docker Compose phase-3
        env:
          COMPOSE_PROFILES: ui
        run: docker compose -f docker-compose/dev_compose.yml up -d