name: local act workflow for feature branch

# For local simulation/testing only!
# Do not use for production deployment.

on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all files
        run: ls -R

      - name: Run Dockerized Tests
        run: make test-all

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all files
        run: ls -R

      - name: Build Docker Images
        run: make build-all

  compose:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker Compose
        run: docker compose -f local/compose/feature-ci.yml up -d
