name: Create and Publish Release

on:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  release:
    runs-on: self-hosted
    # permissions:
    #   contents: read
    #   packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up dynamic VERSION variable from Git Tag
        run: |
          echo "VERSION=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF_NAME} | sed 's/^v//')" >> $GITHUB_ENV
      
      - name: Build and Push all images with Release Version
        run: make push-all