name: PR Quality Check

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  validation:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all files
        run: ls -R

      - name: Build Service Images
        run: make build-all
            
      - name: Build Toolkit Images
        run: make build-tool-all

      - name: Run Unit & Integration Tests
        run: make test-all
      
      - name: Create .env.secret
        run: |
          cat <<EOF > .env.secret
          CLIENT_ID=${{ secrets.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}
          EOF

      - name: Run End-to-End Smoke Test
        run: make smoke-test