name: Run Tests with Docker

on:
  push:
    branches:
      - feature/covid-data-simulator
  workflow_run:
      workflows:
        - Build and Test
      types:
        - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download test data
        uses: actions/download-artifact@v3
        with:
          name: test-data
          path: ./service/CovidDataSimulator/data
      
      - name: check dir
        run: ls -R

      - name: Make the script executable
        run: chmod +x ./scripts/CovidDataSimulator/build_and_test.sh

      - name: Run Dockerized Tests
        run: make build-and-test-covid-simulator 
