name: Run Tests with Docker

on:
  push:
    branches:
      - feature/covid-data-simulator
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: check dir
        run: ls -R

      - name: Make the script executable
        run: chmod +x ./scripts/CovidDataSimulator/build_and_test.sh

      # - name: Run Dockerized Tests
      #   run: make build-and-test-covid-simulator 
